'use client';
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import '../../public/styles/global.scss';
import '../../public/styles/_variables.module.scss';
import '../components/footer/footer.scss';
import withTheme from "../theme";
import {Breadcrumb, Layout, Menu, theme} from "antd";
// import { ReactComponent as Logo} from "../../public/images/logo-no-background.svg";
// import Logo from '../../public/images/svg/logo-color.svg'
import Link from "next/link";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import Image from "next/image";
import {usePathname, useRouter} from "next/navigation";
import {useEffect} from "react";
import AOS from 'aos';
import FooterPage from "../components/footer/Footer";


const {Header, Content} = Layout;

const items = [
    {
        key: "/",
        label: <Link href={'/'}>Home</Link>,
    },
    {
        key: "/about" +
            "'" +
            "" +
            "" +
            "" +
            "",
        label: <Link href={'/about'}>About Us</Link>
    },
    {
        key: "3",
        label: "Menu",
    },
    {
        key: "4",
        label: "Gallery",
    },
    {
        key: "5",
        label: "Contact Us",
    },
    {key: "6", label: "Order Now"},
];

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    const routerPath = usePathname()

    useEffect(() => {
        AOS.init();
    });


    return (
        <html lang="en">
        <body className={inter.className}>
        <AntdRegistry>
            {withTheme(
                <Layout>
                    <Header className={"sticky top-0 z-10 w-full flex items-center"}>
                        <div className="mt-1">

                            <Link href={"/"}>
                                <Image src={'/images/svg/logo-no-background.svg'} alt={'Logo'} width={200} height={64}/>
                                {/*<Logo />*/}
                            </Link>

                        </div>
                        <Menu
                            theme="light"
                            mode="horizontal"
                            className={"flex-1 justify-end"}
                            defaultSelectedKeys={[routerPath]}
                            activeKey={routerPath}
                            items={items}
                        />
                        {/*<Menu*/}
                        {/*    theme="light"*/}
                        {/*    mode="horizontal"*/}
                        {/*    activeKey={router.path.split('/').pop() as string}*/}
                        {/*    items={horizontalRoutes}*/}
                        {/*    className="horizontal-menu"*/}
                        {/*/>*/}
                    </Header>
                    <Content className={"px-0 py-0"}>
                        <div>{children}</div>
                    </Content>
                    <FooterPage/>
                </Layout>,
            )}
        </AntdRegistry>
        </body>
        </html>
    );
}
